---
title: "Interactive Beer"
author: "Richard M. Palmer"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
library(shiny)
library(tidyverse)

beers_raw <- read.csv('Beers.csv') %>% rename(Brew_ID = Brewery_id, Beer_name = Name)
breweries_raw <- read.csv('Breweries.csv') %>% rename(Brewery_name = Name)

# join on Brewery ID and sort the result by Beer ID.
beers <- inner_join(beers_raw, breweries_raw,by='Brew_ID') %>% arrange(Beer_ID)
states <- levels(beers$State)

ui <- fluidPage(
  titlePanel("Beer"),
  sidebarLayout(
    sidebarPanel(
      tags$div(class="header",checked=NA,tags$p("About Plot 1")),
      selectInput(inputId="which_plot",
                  label="What type of Plot?",
                  choices=list("Histogram"="hist","BoxPlot"="box"),
                  selected=1),
      sliderInput(inputId="bins",
                  label="Number of bins",
                  min=1,
                  max=50,
                  value=25),
      selectInput(inputId="which_var",
                  label="Which Variable?",
                  choices=list("ABV"="abv","IBU"="ibu"),
                  selected=1),
      checkboxInput(inputId="hist_filter","Filter by State",FALSE),
      selectInput(inputId="hist_state",
                  label="Which State?",
                  choices=states),
      tags$div(class="header",checked=NA,tags$p("About Plot 2")),
      checkboxInput(inputId="trend_line","Draw Regression Line",FALSE),
      checkboxInput(inputId="scat_filter","Filter by State",FALSE),
      selectInput(inputId="scat_state",
                  label="Which State?",
                  choices=states)
    ),
    mainPanel(
      plotOutput(outputId="distPlot"),
      plotOutput(outputId="scatPlot")
    )
  )
)

server <- function(input,output) {
  output$distPlot <- renderPlot({
    if (input$hist_filter) {
      hist_data <- subset(beers,State == input$hist_state)
      modifier <- paste("in",input$hist_state)
    } else {
      hist_data <- beers
      modifier <- "all states"
    }
    if (input$which_var == "abv")
    {
      x <- hist_data$ABV
    }
    if (input$which_var == "ibu")
    {
      x <- hist_data$IBU
    }
    if (input$which_plot == "hist")
    {
    hist(x,breaks=input$bins,col="#75AADB",border="white",
         xlab=input$which_var,
         main=(paste("Histogram",modifier)))
    }
    if (input$which_plot == "box")
    {
      boxplot(x,main=paste("Distribution of",input$which_var,modifier))
    }
  })
  output$scatPlot <- renderPlot({
    if (input$scat_filter) {
      scat_data <- subset(beers,State == input$scat_state)
      modifier <- paste("in",input$scat_state)
    } else {
      scat_data <- beers
      modifier <- "all states"
    }
    plot(x=scat_data$ABV,
         y=scat_data$IBU,
         xlab="ABV",
         ylab="IBU",
         main=paste("Bitterness vs Alchohol",modifier))
    if (input$trend_line) 
    {
      reg1 <- lm(IBU~ABV,data=scat_data)
      abline(reg1)
    }
  })
}

shinyApp(ui,server)

```
